  
# The log file location   
log:
filename: "syllus.log"

# All the databases used by the system
databases:
  dev: "data/syllus.sqlite"
  stage: ""
  prod: "data/syllus.sqlite"

databaseAdmin:
  user: 'hopperg'
  
# For every table in the database, add an item here
models:
  mainDB:
    - Semesters
    - Divisions
    - Programs
    - Users
    - Courses
    - UsersCourses
    - Deadline
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/courses"
  - title: "Archive"
    link: "/archive"
  - title: "Log Out"
    link: "/" #TODO_LOGOUT:  We need the page for logout purposes
    
adminMenu:
  Administration:
    - title: "Program Management"
      link:  "/redirect/program_management"
    - title: "Division Management"
      link:  "/redirect/division_management"
    - title: "System Management"
      link:  "/admin/systemManagement"
    - title: "Course Management"
      link:  "/admin/courseManagement/missingSyllabi"

courseManagementSidebar:
  - title: "Missing Syllabi"
    link:  "/admin/courseManagement/missingSyllabi"
  - title: "Add Course"
    link: "/admin/courseManagement/addCourse"
  - title: "Remove Course"
    link: "/admin/courseManagement/removeCourse"
    
Headers:
  Courses: ['Instructor','Course','Term','Syllabus Upload','Last Modified By']
  Archive: ['Instructor','Course','Term','Last Modified By']
    
fileOperations:
  allowedExtension:
      pdf: "pdf"
      doc: "doc"
      docx: "docx"
  allowedSize:
      size: 8000000
  dataPaths:
      uploads: "app/static/files/uploads"
      zips: "static/files/zips"
      tmp: "app/static/files/tmp"
      download: "static/files/uploads"

termInfo:
#the keys correlate to the last two digits in the term code eg: Fall 2016 = 201611 
    11: 'Fall'              # e.g. Fall 2016 = 201611
    12: 'Spring'            # e.g. Spring 2017 = 201612 (note the different year)
    13: 'Summer'            
    #NOTE: Replace the 3 summer terms with just summer 20180612
    #13: '8 Week Summer'     # e.g. 8 Week Summer 2017 = 201613 (note the different year)
    #14: '1st 4 Week Summer'
    #15: '2nd 4 Week Summer'
    #10: 'The Bridge Program'   # e.g. Bridge Program 2016 = 201610 
    
DEBUG:
  user: "hopperg@email.com" #Admin Access
  # user: "turinga" #Division Chair Access
  # user: "borga"  #Professor Access
  # user: "doej" #Program Access
  
# contributors: TODO: Add the names and graduation year of the contributors here e.g. 
#   - name: "Alice Bob"
#     username: "boba"
#     year: 2018
#   - 